---
- name: My Playbook
  hosts: all
  tasks:
    - name: Set global variables
      ansible.builtin.set_fact:
        var1: Hello
        var2: Turtles

- name: First Play
  hosts: all
  tasks:
    - name: Use global variables
      ansible.builtin.debug:
        msg: "{{ var1 }} {{ var2 }}"
